extends RefCounted
class_name RegionData

static func get_regions() -> Dictionary:
	return {
		"r1": {"name": "청람 성채", "owner": 0, "pos": Vector2(390, 325), "adjacent": ["t1", "t2", "t3", "t4", "t5", "r2", "r4"], "danger": "낮음", "recommended": "기본 병력", "encounter_type": "castle", "expected_enemy_classes": ["infantry"], "reward_preview": "거점 정비", "reward_focus": "내정", "economy_role": "출정 거점 유지", "suggested_use": "병력 재정비와 다음 출정을 준비하세요.", "reward": {"gold": 40, "supplies": 10, "materials": 10, "renown": 0, "companion_exp": 20}},
		"t1": {"name": "낡은 훈련장", "owner": 1, "pos": Vector2(500, 230), "adjacent": ["r1", "t2", "t6"], "danger": "매우 낮음", "recommended": "기본 병력 / 훈련", "encounter_type": "training", "action_type": "training", "objective_type": "unlock", "event_id": "event_t1_training", "event_status": "open", "encounter_flavor": "청람 신병들이 흩어진 채 훈련장을 점거하고 있습니다.", "special_rule": "창병 해금", "expected_enemy_classes": ["infantry"], "reward_preview": "창병 해금 / 동료 EXP / 소량 금화", "reward_focus": "병종 해금", "economy_role": "병종 해금 / 훈련", "suggested_use": "창병 해금으로 초반 상성 대응을 준비하세요.", "unlock_class": "spearman", "reward": {"gold": 20, "supplies": 5, "materials": 5, "renown": 1, "companion_exp": 25}},
		"t2": {"name": "버려진 농가", "owner": 2, "pos": Vector2(520, 360), "adjacent": ["r1", "t1", "t4", "r2"], "danger": "낮음", "recommended": "기본 병력", "encounter_type": "bandit", "action_type": "choice", "objective_type": "choice", "event_id": "event_t2_farm_choice", "event_status": "open", "encounter_flavor": "약탈로 텅 빈 농가에서 생존자와 보급이 동시에 발견됩니다.", "special_rule": "보급 확보 또는 명성 선택 later", "expected_enemy_classes": ["infantry"], "reward_preview": "보급 대량 획득 / 금화", "reward_focus": "보급", "economy_role": "초반 출정 유지 자원 확보", "suggested_use": "보급을 모아 연속 출정과 회복에 대비하세요.", "reward": {"gold": 35, "supplies": 35, "materials": 5, "renown": 2, "companion_exp": 20}},
		"t3": {"name": "무너진 초소", "owner": 1, "pos": Vector2(350, 235), "adjacent": ["r1", "t1", "r2"], "danger": "낮음", "recommended": "기본 병력 + 전열 유지", "encounter_type": "frontier", "action_type": "resource", "objective_type": "unlock", "event_id": "event_t3_outpost_unlock", "event_status": "open", "encounter_flavor": "붕괴된 보급 초소에 남은 설계도와 자재를 확보해야 합니다.", "special_rule": "방패보병 해금", "expected_enemy_classes": ["infantry", "archer"], "reward_preview": "방패보병 해금 / 자재", "reward_focus": "자재", "economy_role": "자재 확보 / 방어 병종 해금", "suggested_use": "자재를 모아 병영 강화와 방패보병 운용을 준비하세요.", "unlock_class": "shieldbearer", "reward": {"gold": 25, "supplies": 10, "materials": 35, "renown": 2, "companion_exp": 22}},
		"t4": {"name": "들개 숲길", "owner": 2, "pos": Vector2(390, 430), "adjacent": ["r1", "t2", "t5", "r4"], "danger": "낮음", "recommended": "훈련장 Lv.1", "encounter_type": "beast", "action_type": "ambush", "objective_type": "rout", "event_id": "event_t4_wild_ambush", "event_status": "open", "encounter_flavor": "숲길의 들개 무리가 선봉대를 기습합니다.", "special_rule": "빠른 야수형 적", "expected_enemy_classes": ["cavalry", "infantry"], "reward_preview": "보급 / 동료 EXP", "reward_focus": "경험치", "economy_role": "경험치 / 보급", "suggested_use": "동료 EXP와 보급을 함께 확보해 전투 지속력을 높이세요.", "reward": {"gold": 25, "supplies": 25, "materials": 10, "renown": 2, "companion_exp": 30}},
		"t5": {"name": "난민 야영지", "owner": 0, "pos": Vector2(310, 500), "adjacent": ["r1", "t4", "r4"], "danger": "이벤트", "recommended": "보급 여유 확보", "encounter_type": "quest", "action_type": "choice", "objective_type": "choice", "event_id": "event_t5_refugee_choice", "event_status": "open", "encounter_flavor": "전투보다 선택과 명성이 중요한 장소입니다.", "special_rule": "명성 중심 선택 이벤트", "expected_enemy_classes": ["infantry"], "reward_preview": "명성 대량 획득 / 후속 성직자 단서", "reward_focus": "명성", "economy_role": "명성 확보 / 신뢰 형성", "suggested_use": "명성으로 향후 동료·해금 조건을 충족할 기반을 만드세요.", "reward": {"gold": 10, "supplies": 10, "materials": 5, "renown": 12, "companion_exp": 15}},
		"t6": {"name": "붉은 깃발 정찰대", "owner": 1, "pos": Vector2(685, 300), "adjacent": ["t1", "r2"], "danger": "보통", "recommended": "창병/방패보병 1개 이상", "encounter_type": "crimson_scout", "action_type": "ambush", "objective_type": "rout", "event_id": "event_t6_scout_ambush", "event_status": "open", "encounter_flavor": "진홍 공국의 정찰대가 숲길에 매복해 있습니다.", "special_rule": "북부 감시요새 전 정찰대", "expected_enemy_classes": ["infantry", "archer"], "reward_preview": "균형 보상 / 북부 감시요새 준비", "reward_focus": "균형", "economy_role": "메인 전투 전 종합 준비", "suggested_use": "북부 감시요새 전투 전 자원과 동료 전력을 고르게 갖추세요.", "reward": {"gold": 65, "supplies": 20, "materials": 25, "renown": 6, "companion_exp": 32}},
		"r2": {"id": "r2", "display_name": "북부 감시요새", "name": "북부 감시요새", "owner_faction": 1, "owner": 1, "is_discovered": true, "is_unlocked": true, "pos": Vector2(760, 210), "adjacent": ["r1", "t2", "t3", "t6", "r3", "r5", "s1"], "danger": "보통", "recommended": "병영 Lv.2 / 방패보병 준비", "encounter_type": "fortress", "action_type": "conquest", "objective_type": "rout", "event_id": "event_r2_fortress", "event_status": "open", "encounter_flavor": "가론이 버티고 있는 북부의 전초 요새입니다.", "special_rule": "가론 합류", "expected_enemy_classes": ["infantry", "shieldbearer", "archer"], "reward_preview": "가론 합류 이벤트 / 명성 / 자재", "reward_focus": "동료", "economy_role": "첫 동료 영입 / 메인 관문", "suggested_use": "가론 합류 이후 성채 전력을 확장하고 다음 관문을 준비하세요.", "reward": {"gold": 90, "supplies": 25, "materials": 30, "renown": 10, "companion_exp": 40}},
		"r3": {"id": "r3", "display_name": "서리숲 관문", "name": "서리숲 관문", "owner_faction": 1, "owner": 1, "is_discovered": true, "is_unlocked": true, "pos": Vector2(820, 300), "adjacent": ["r2", "r6", "s3"], "danger": "높음", "recommended": "훈련장 Lv.2", "encounter_type": "frontier", "action_type": "conquest", "objective_type": "survive_or_rout", "event_id": "event_r3_gate", "event_status": "open", "encounter_flavor": "서리숲 관문은 길목이 좁아 버티기와 돌파가 동시에 요구됩니다.", "special_rule": "엘린 합류", "expected_enemy_classes": ["archer", "infantry"], "reward": {"gold": 100, "supplies": 22, "materials": 30, "renown": 12, "companion_exp": 40}},
		"r4": {"name": "서부 협곡로", "owner": 0, "pos": Vector2(475, 515), "adjacent": ["r1", "t4", "t5", "r5", "r7", "s2"], "danger": "보통", "recommended": "병영 Lv.2", "encounter_type": "frontier", "expected_enemy_classes": ["infantry"], "reward": {"gold": 70, "supplies": 18, "materials": 20, "renown": 4, "companion_exp": 30}},
		"r5": {"name": "중앙 평원", "owner": 2, "pos": Vector2(670, 470), "adjacent": ["r2", "r4", "r6", "r8"], "danger": "높음", "recommended": "병영 Lv.2 + 훈련장 Lv.2", "encounter_type": "field", "expected_enemy_classes": ["infantry", "cavalry"], "reward": {"gold": 120, "supplies": 26, "materials": 35, "renown": 10, "companion_exp": 45}},
		"r6": {"name": "남해 항구", "owner": 2, "pos": Vector2(810, 520), "adjacent": ["r3", "r5"], "danger": "높음", "recommended": "훈련장 Lv.2", "encounter_type": "coast", "expected_enemy_classes": ["infantry", "archer"], "reward": {"gold": 110, "supplies": 24, "materials": 28, "renown": 9, "companion_exp": 42}},
		"r7": {"id": "r7", "display_name": "고대 유적지", "name": "고대 유적지", "owner_faction": 0, "owner": 0, "is_discovered": true, "is_unlocked": true, "pos": Vector2(380, 640), "adjacent": ["r4", "r8"], "danger": "높음", "recommended": "엘린 합류 / 방패보병 / 보급 확보", "encounter_type": "ruin_magic", "action_type": "exploration", "objective_type": "investigate", "region_event_id": "ancient_ruins_mira", "event_id": "ancient_ruins_mira", "event_status": "open", "encounter_flavor": "청람 영토 안에 있지만, 유적 내부의 마법진은 아직 조사되지 않았습니다.", "special_rule": "미라 합류 / 소서러 해금", "expected_enemy_classes": ["infantry", "sorcerer"], "reward_preview": "미라 합류 이벤트 / 소서러 해금 / 자재", "suggested_use": "유적 조사로 미라와 소서러 전력을 확보하세요.", "reward": {"gold": 95, "supplies": 22, "materials": 36, "renown": 9, "companion_exp": 44}},
		"r8": {"name": "녹림 산맥", "owner": 2, "pos": Vector2(650, 640), "adjacent": ["r5", "r7"], "danger": "높음", "recommended": "병영 Lv.2 + 숙소 Lv.2", "encounter_type": "mountain", "expected_enemy_classes": ["infantry", "archer", "cavalry"], "reward": {"gold": 130, "supplies": 28, "materials": 40, "renown": 13, "companion_exp": 48}},
		"s1": {"name": "버려진 광산", "owner": 1, "pos": Vector2(760, 120), "adjacent": ["r2"], "danger": "낮음", "recommended": "기본 병력", "encounter_type": "bandit", "expected_enemy_classes": ["infantry"], "reward": {"gold": 30, "supplies": 12, "materials": 55, "renown": 2, "companion_exp": 20}},
		"s2": {"name": "난민 수레길", "owner": 2, "pos": Vector2(120, 470), "adjacent": ["r4"], "danger": "낮음", "recommended": "숙소 Lv.1", "encounter_type": "quest", "expected_enemy_classes": ["infantry"], "reward": {"gold": 35, "supplies": 16, "materials": 12, "renown": 18, "companion_exp": 22}},
		"s3": {"name": "늑대 숲", "owner": 2, "pos": Vector2(840, 335), "adjacent": ["r3"], "danger": "보통", "recommended": "훈련장 Lv.1", "encounter_type": "beast", "expected_enemy_classes": ["cavalry", "infantry"], "reward": {"gold": 85, "supplies": 20, "materials": 16, "renown": 6, "companion_exp": 34}}
	}
