extends RefCounted
class_name RegionData

static func get_regions() -> Dictionary:
	return {
		"r1": {"name": "청람 성채", "owner": 0, "pos": Vector2(340, 300), "adjacent": ["t1", "t2", "t3", "t4", "t5", "r2", "r4"], "danger": "낮음", "recommended": "기본 병력", "encounter_type": "castle", "expected_enemy_classes": ["infantry"], "reward_preview": "거점 정비", "reward_focus": "내정", "economy_role": "출정 거점 유지", "suggested_use": "병력 재정비와 다음 출정을 준비하세요.", "reward": {"gold": 40, "supplies": 10, "materials": 10, "renown": 0, "companion_exp": 20}},
		"t1": {"name": "낡은 훈련장", "owner": 1, "pos": Vector2(430, 220), "adjacent": ["r1", "t2", "t6"], "danger": "매우 낮음", "recommended": "기본 병력 / 훈련", "encounter_type": "training", "expected_enemy_classes": ["infantry"], "reward_preview": "창병 해금 / 동료 EXP / 소량 금화", "reward_focus": "병종 해금", "economy_role": "병종 해금 / 훈련", "suggested_use": "창병 해금으로 초반 상성 대응을 준비하세요.", "unlock_class": "spearman", "reward": {"gold": 20, "supplies": 5, "materials": 5, "renown": 1, "companion_exp": 25}},
		"t2": {"name": "버려진 농가", "owner": 2, "pos": Vector2(500, 340), "adjacent": ["r1", "t1", "t4", "r2"], "danger": "낮음", "recommended": "기본 병력", "encounter_type": "bandit", "expected_enemy_classes": ["infantry"], "reward_preview": "보급 대량 획득 / 금화", "reward_focus": "보급", "economy_role": "초반 출정 유지 자원 확보", "suggested_use": "보급을 모아 연속 출정과 회복에 대비하세요.", "reward": {"gold": 35, "supplies": 35, "materials": 5, "renown": 2, "companion_exp": 20}},
		"t3": {"name": "무너진 초소", "owner": 1, "pos": Vector2(260, 220), "adjacent": ["r1", "t1", "r2"], "danger": "낮음", "recommended": "기본 병력 + 전열 유지", "encounter_type": "frontier", "expected_enemy_classes": ["infantry", "archer"], "reward_preview": "방패보병 해금 / 자재", "reward_focus": "자재", "economy_role": "자재 확보 / 방어 병종 해금", "suggested_use": "자재를 모아 병영 강화와 방패보병 운용을 준비하세요.", "unlock_class": "shieldbearer", "reward": {"gold": 25, "supplies": 10, "materials": 35, "renown": 2, "companion_exp": 22}},
		"t4": {"name": "들개 숲길", "owner": 2, "pos": Vector2(370, 405), "adjacent": ["r1", "t2", "t5", "r4"], "danger": "낮음", "recommended": "훈련장 Lv.1", "encounter_type": "beast", "expected_enemy_classes": ["cavalry", "infantry"], "reward_preview": "보급 / 동료 EXP", "reward_focus": "경험치", "economy_role": "경험치 / 보급", "suggested_use": "동료 EXP와 보급을 함께 확보해 전투 지속력을 높이세요.", "reward": {"gold": 25, "supplies": 25, "materials": 10, "renown": 2, "companion_exp": 30}},
		"t5": {"name": "난민 야영지", "owner": 0, "pos": Vector2(245, 415), "adjacent": ["r1", "t4", "r4"], "danger": "이벤트", "recommended": "보급 여유 확보", "encounter_type": "quest", "expected_enemy_classes": ["infantry"], "reward_preview": "명성 대량 획득 / 후속 성직자 단서", "reward_focus": "명성", "economy_role": "명성 확보 / 신뢰 형성", "suggested_use": "명성으로 향후 동료·해금 조건을 충족할 기반을 만드세요.", "reward": {"gold": 10, "supplies": 10, "materials": 5, "renown": 12, "companion_exp": 15}},
		"t6": {"name": "붉은 깃발 정찰대", "owner": 1, "pos": Vector2(615, 235), "adjacent": ["t1", "r2"], "danger": "보통", "recommended": "창병/방패보병 1개 이상", "encounter_type": "crimson_scout", "expected_enemy_classes": ["infantry", "archer"], "reward_preview": "균형 보상 / 북부 감시요새 준비", "reward_focus": "균형", "economy_role": "메인 전투 전 종합 준비", "suggested_use": "북부 감시요새 전투 전 자원과 동료 전력을 고르게 갖추세요.", "reward": {"gold": 65, "supplies": 20, "materials": 25, "renown": 6, "companion_exp": 32}},
		"r2": {"name": "북부 감시요새", "owner": 1, "pos": Vector2(700, 145), "adjacent": ["r1", "t2", "t3", "t6", "r3", "r5", "s1"], "danger": "보통", "recommended": "병영 Lv.2 / 방패보병 준비", "encounter_type": "fortress", "expected_enemy_classes": ["infantry", "shieldbearer", "archer"], "reward_preview": "가론 합류 이벤트 / 명성 / 자재", "reward_focus": "동료", "economy_role": "첫 동료 영입 / 메인 관문", "suggested_use": "가론 합류 이후 성채 전력을 확장하고 다음 관문을 준비하세요.", "reward": {"gold": 90, "supplies": 25, "materials": 30, "renown": 10, "companion_exp": 40}},
		"r3": {"name": "서리숲 관문", "owner": 1, "pos": Vector2(730, 210), "adjacent": ["r2", "r6", "s3"], "danger": "높음", "recommended": "훈련장 Lv.2", "encounter_type": "frontier", "expected_enemy_classes": ["archer", "infantry"], "reward": {"gold": 100, "supplies": 22, "materials": 30, "renown": 12, "companion_exp": 40}},
		"r4": {"name": "서부 협곡로", "owner": 0, "pos": Vector2(290, 410), "adjacent": ["r1", "t4", "t5", "r5", "r7", "s2"], "danger": "보통", "recommended": "병영 Lv.2", "encounter_type": "frontier", "expected_enemy_classes": ["infantry"], "reward": {"gold": 70, "supplies": 18, "materials": 20, "renown": 4, "companion_exp": 30}},
		"r5": {"name": "중앙 평원", "owner": 2, "pos": Vector2(560, 390), "adjacent": ["r2", "r4", "r6", "r8"], "danger": "높음", "recommended": "병영 Lv.2 + 훈련장 Lv.2", "encounter_type": "field", "expected_enemy_classes": ["infantry", "cavalry"], "reward": {"gold": 120, "supplies": 26, "materials": 35, "renown": 10, "companion_exp": 45}},
		"r6": {"name": "남해 항구", "owner": 2, "pos": Vector2(760, 390), "adjacent": ["r3", "r5"], "danger": "높음", "recommended": "훈련장 Lv.2", "encounter_type": "coast", "expected_enemy_classes": ["infantry", "archer"], "reward": {"gold": 110, "supplies": 24, "materials": 28, "renown": 9, "companion_exp": 42}},
		"r7": {"name": "고대 유적지", "owner": 0, "pos": Vector2(240, 610), "adjacent": ["r4", "r8"], "danger": "높음", "recommended": "엘린 합류 / 방패보병 / 보급 확보", "encounter_type": "ruin_magic", "expected_enemy_classes": ["infantry", "sorcerer"], "reward_preview": "미라 합류 이벤트 / 소서러 해금 / 자재", "reward": {"gold": 95, "supplies": 22, "materials": 36, "renown": 9, "companion_exp": 44}},
		"r8": {"name": "녹림 산맥", "owner": 2, "pos": Vector2(540, 610), "adjacent": ["r5", "r7"], "danger": "높음", "recommended": "병영 Lv.2 + 숙소 Lv.2", "encounter_type": "mountain", "expected_enemy_classes": ["infantry", "archer", "cavalry"], "reward": {"gold": 130, "supplies": 28, "materials": 40, "renown": 13, "companion_exp": 48}},
		"s1": {"name": "버려진 광산", "owner": 1, "pos": Vector2(825, 65), "adjacent": ["r2"], "danger": "낮음", "recommended": "기본 병력", "encounter_type": "bandit", "expected_enemy_classes": ["infantry"], "reward": {"gold": 30, "supplies": 12, "materials": 55, "renown": 2, "companion_exp": 20}},
		"s2": {"name": "난민 수레길", "owner": 2, "pos": Vector2(120, 470), "adjacent": ["r4"], "danger": "낮음", "recommended": "숙소 Lv.1", "encounter_type": "quest", "expected_enemy_classes": ["infantry"], "reward": {"gold": 35, "supplies": 16, "materials": 12, "renown": 18, "companion_exp": 22}},
		"s3": {"name": "늑대 숲", "owner": 2, "pos": Vector2(800, 240), "adjacent": ["r3"], "danger": "보통", "recommended": "훈련장 Lv.1", "encounter_type": "beast", "expected_enemy_classes": ["cavalry", "infantry"], "reward": {"gold": 85, "supplies": 20, "materials": 16, "renown": 6, "companion_exp": 34}}
	}
